tradingbook/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("tradingbookapp.urls"))
]


urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

tradingbookapp/urls.py
from django.urls import path

from . import views #se utiliza el punto por que es la ruta relativa (donde esta la carpeta)

urlpatterns = [
    path('',views.index, name='Home'),
    path('dashboard/',views.Dashboard,name="Dashboard"),
    path('login',views.Login_request,name="Login"),
    path('register',views.Register_request,name="Register"),
    path('logout',views.Logout_request,name="Logout"),
    path('editar_perfil',views.Editar_perfil,name="Editar_perfil"),
    path('agregar_avatar',views.Agregar_avatar,name="Agregar_avatar"),
    path('profile',views.Profile,name="Profile"),
    
    
    
    
    path('eliminar_trade/<trade_id>',views.eliminar_trade,name="Eliminar_trade"),
    path('editar_trade/<trade_id>',views.editar_trade,name="Editar_trade"),
    path('ver_trade/<trade_id>',views.ver_trade,name="Ver_trade"),
    
    #Nuevas URLS
    path('trades/list',views.TradesList.as_view(),name="Trades_list"),
    path('trades/<pk>',views.TradesDetail.as_view(),name="Trades_detail"),
    path('trade/nuevo',views.TradeCreate.as_view(),name="Trades_create"),
    path('trades/editar/<pk>',views.TradeUpdate.as_view(),name="Trades_update"),
    path('trades/eliminar/<pk>',views.TradeDelete.as_view(),name="Trades_delete"),
    
    
    
    
    path('notes/',views.Notes,name="Notes"),
    path('trades/',views.Trades,name="Trades"),
    path('markets/',views.Markets,name="Markets"),
    path('challenge/',views.Challenge,name="Challenge"),
    path('crear_trades/',views.crear_trade,name="crear_trades"),
    path('buscar_trades/',views.buscar_trade,name="buscar_trades"),
    path('buscar_notes/',views.buscar_note,name="buscar_notes"),
    path('buscar_mercados/',views.buscar_mercado,name="buscar_trades"),
    path('crear_notes/',views.crear_notes,name="crear_notes"),
    path('crear_mercados/',views.crear_mercados,name="crear_mercados"),
    
    
    
    
    
    # path('base/', views.base),
    
]

tradingbookapp/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User

#modelo del avatar 
class Avatar(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='avatar/',blank=True,null=True)
# para  este modelo tuvimos que crear una carpeta media a nivel de manage.py y ademas registramos su URL en la carpeta setting 


class Trade(models.Model):
    fecha = models.DateField("Fecha de operacion (mm/dd/yyyy)",auto_now_add=False,auto_now=False,blank=True,null=True)
    simbolo = models.CharField("Simbolo",max_length=30)
    
    posiciones = (
        (1,"Long"),
        (2,"Short")
    )
    posicion = models.PositiveSmallIntegerField("Posicion",choices=posiciones)
    entrada = models.FloatField("Precio Entrada",)
    target = models.FloatField("Target")
    stop = models.FloatField("stop")
    tradeimagen = models.ImageField(upload_to='tradesimagen/',blank=True,null=True)
    

class Note(models.Model):
    fecha = models.DateField("Fecha de operacion (mm/dd/yyyy)",auto_now_add=False,auto_now=False,blank=True,null=True)
    simbolo = models.CharField("Simbolo",max_length=30)
    nota = models.CharField("Notas de trading", max_length=250)
    
    
class  Market(models.Model):
    pais = models.CharField("pais a donde pertenece",max_length=30)
    simbolo = models.CharField("Simbolo a observar",max_length=30)
    


class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    imagenavatar = models.ImageField(upload_to='avatar/',blank=True,null=True)
    bio = models.TextField()
    
    def __str__(self):
        return self.user.username
    
    
class Tradeimagen(models.Model): # esto no esta bien por que estoy relacionando con un usuario, asi se haria para mostrar solo lo que mostro ese usuraio 
    usuario = models.OneToOneField(User, on_delete=models.CASCADE) #pendiente!!!!!
    tradeimagen = models.ImageField(upload_to='tradesimagen/',blank=True,null=True)

tradingbookapp/forms.py
from django import forms
from django.forms.widgets import NumberInput
from django.contrib.auth.forms import AuthenticationForm , UserCreationForm #formulario de autenticacion 
from django.contrib.auth.models import User
from .models import Avatar,Tradeimagen


posiciones=(
    ("1","Long"),
    ("2","Short"),
    
)
class NuevoTrade(forms.Form):
    fecha = forms.DateTimeField(label="fecha ", required=True, widget=NumberInput(attrs={'type':'date'}))
    simbolo = forms.CharField(label="simbolo")
    posicion = forms.ChoiceField(label="posicion",choices=posiciones)
    entrada = forms.FloatField(label="Precio Entrada",)
    target = forms.FloatField(label="Target")
    stop = forms.FloatField(label="stop")
    tradeimagen = forms.ImageField(label="tradeimagen",required=False)
    

    

class NuevaTradingnote(forms.Form):
    fecha = forms.DateTimeField(label="fecha ", required=True, widget=NumberInput(attrs={'type':'date'}))
    simbolo = forms.CharField(label="simbolo")
    nota = forms.CharField(label="Nota",widget=forms.Textarea(attrs={"rows":5, "cols":30}))


class NuevoMercado(forms.Form):
    pais =forms.CharField(label="pais")
    simbolo = forms.CharField(label="simbolo")
    
    
class UserRegisterform(UserCreationForm):
    
    
    foto = forms.ImageField(required=False)
    
    email = forms.EmailField(label="Email")
    password1 = forms.CharField(label="Password",widget=forms.PasswordInput) # lacontrasena no se ve 
    password2: forms.CharField(label="Password",widget=forms.PasswordInput)
    
    first_name = forms.CharField(label='Nombre',required=False)
    last_name=forms.CharField(label='Apellido',required=False)
    
    
    class Meta:
        model = User 
        fields=['username','email','password1','password2','first_name','last_name']
        # help_texts = {k:"" for k in fields}
    
class UserEditForm(UserCreationForm):
    email=forms.EmailField(label="Email")  
    password1 = forms.CharField(label="Password",widget=forms.PasswordInput,required=False) # lacontrasena no se ve 
    password2: forms.CharField(label="Confirmar Password",widget=forms.PasswordInput,required=False)
    first_name = forms.CharField(label='Nombre')
    last_name=forms.CharField(label='Apellido')
    
    
    
    class Meta:
        model = User
        fields = ["email",'password1','password2','first_name','last_name']
        
        
class AvatarForm(forms.Form):
    imagen = forms.ImageField(label="imagen",required=False)
    
    class Meta:
        model = Avatar
        fields = ["imagen"]
        
        

tradingbookapp/views.py
from dataclasses import dataclass
import re
from django.shortcuts import render,redirect
from .models import Avatar, Trade,Note,Market
from .forms import NuevoTrade,NuevaTradingnote,NuevoMercado
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView,UpdateView,DeleteView

from django.contrib.auth.forms import AuthenticationForm   , UserCreationForm #formulario de autenticacion 
from .forms import *
from django.contrib.auth import login,logout, authenticate
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required




@login_required
def Agregar_avatar(request):
    
    if request.method == 'POST':
        
        form = AvatarForm(request.POST,request.FILES)
        
        
        if form.is_valid():
            
            user = User.objects.get(username=request.user) # usuario con el que estamos login 
            
            avatar = Avatar(usuario = user,imagen=form.cleaned_data['imagen']) # relacionar una imagen con un usuario especifico 
            
            # avatar = Avatar()
            # avatar.usuario = request.user
            # avatar.imagen = form.cleaned_data['image']
            avatar.save()
            
            return redirect('Home')
        
    else:
        form = AvatarForm()
        
    return render(request,'tradingbookapp/agregar_avatar.html',{'form':form})
        
        

def buscar_trade(request):
    if request.method == "POST":
        simbolo=request.POST["simbolo"]
        
        trades = Trade.objects.filter(simbolo__icontains=simbolo)
        return render(request,'tradingbookapp/buscar_trade.html',{"trades":trades})
    
    
    else: #GET Y otros
        trades = []
        return render(request,'tradingbookapp/buscar_trade.html',{"trades":trades})


def buscar_note(request):
    
    
    notesexistente = []
    return render(request,'tradingbookapp/buscar_note.html',{"trades":notesexistente})


def buscar_mercado(request):
    mercadosexistente = []
    return render(request,'tradingbookapp/buscar_mercado.html',{"trades":mercadosexistente})


def base(request):
    
    return render(request,'tradingbookapp/base.html',{})


def Challenge(request):
    return render (request,'tradingbookapp/challenge.html')

@staff_member_required
def crear_trade(request):
    
    if request.method =="POST":
        #post
        formulario = NuevoTrade(request.POST,request.FILES)
        if formulario.is_valid():
            
            info_trade = formulario.cleaned_data
            
            trade = Trade(fecha = request.POST['fecha'],simbolo = request.POST['simbolo'],posicion = request.POST['posicion'],entrada = request.POST['entrada'],target = request.POST['target'], stop = request.POST['stop'],tradeimagen=request.POST['tradeimagen'])
            trade.save()
            return redirect("Trades")
        
        else:
            return render(request,'tradingbookapp/formulario_trade.html',{"form":formulario})
        
    else: #get y otros:
        
        tradevacio = NuevoTrade()
        
        
        return render(request,'tradingbookapp/formulario_trade.html',{"form":tradevacio})


def crear_notes(request):
    
    if request.method =="POST":
        #post
        formulario = NuevaTradingnote(request.POST)
        if formulario.is_valid():
            
            info_note = formulario.cleaned_data
            note = Note(fecha = request.POST['fecha'],simbolo = request.POST['simbolo'],nota = request.POST['nota'])
            note.save()
            return redirect("Home")
        else:
            return render(request,'tradingbookapp/formulario_notes.html',{"form":formulario})
        
    else:
        notavacia = NuevaTradingnote()
        return render(request,'tradingbookapp/formulario_notes.html',{"form":notavacia})


def crear_mercados(request):
    if request.method =="POST":
        #post
        formulario = NuevoMercado(request.POST)
        if formulario.is_valid():

            mercado = Market(pais= request.POST['pais'],simbolo= request.POST['simbolo'])
            mercado.save()
            return redirect("Home")
        else:
            return render(request,'tradingbookapp/formulario_mercados.html',{"form":formulario})
            
    else:  
        mercadovacio = NuevoMercado()  
        return render(request,'tradingbookapp/formulario_mercados.html',{"form":mercadovacio})


def Dashboard(request):
    
    trades = Trade.objects.all()
    ctx = {'trades':trades}
    return  render (request,'tradingbookapp/dashboard.html',ctx)

@login_required
def Editar_perfil(request):
    
    user = request.user # usuario con el que estamos loging
    
    if request.method =="POST":
        
        form = UserEditForm(request.POST)
        
        if form.is_valid():
            
            info = form.cleaned_data
            user.email = info["email"]
            user.first_name = info['first_name']
            user.last_name = info['last_name']
            user.save()
            
            return redirect("Home")
              
    
    else:
        form = UserEditForm(initial={'email':user.email,"first_name":user.first_name,'last_name':user.last_name})
    
    return render(request,'tradingbookapp/editar_perfil.html',{'form':form})


@staff_member_required
def eliminar_trade(request,trade_id):
    trade = Trade.objects.get(id=trade_id)
    trade.delete()
    return redirect("Trades")


@login_required
def ver_trade(request,trade_id):
    trade = Trade.objects.get(id=trade_id)
    ctx = {'trade':trade}
    
    return render(request,'tradingbookapp/ver_trade.html',ctx)
    
    

@staff_member_required
def editar_trade(request,trade_id):
    trade = Trade.objects.get(id=trade_id)
    if request.method == "POST":
        formulario = NuevoTrade(request.POST)
        if formulario.is_valid():
            info_trade = formulario.cleaned_data
            trade.fecha = info_trade["fecha"]
            trade.simbolo = info_trade["simbolo"]
            trade.posicion = info_trade["posicion"]
            trade.entrada = info_trade["entrada"]
            trade.target = info_trade["target"]
            trade.stop = info_trade["stop"]
            trade.save()
            
            return redirect("Trades")
        
    
    
    formulario = NuevoTrade(initial={"fecha":trade.fecha,"simbolo":trade.simbolo,"posicion":trade.posicion,"entrada":trade.entrada,"target":trade.target,"stop":trade.stop,})
   
    return render(request,'tradingbookapp/formulario_trade.html',{"form":formulario})
    

def index(request):
    
    
    if request.user.is_authenticated:
        try:
            avatar= Avatar.objects.get(usuario=request.user)
            url = avatar.imagen.url
        except:
            url ='/media/avatar/generica.png'
        return render (request,'tradingbookapp/index.html',{"url":url})
            
    
        
        
        
    return render (request,'tradingbookapp/index.html')


def Login_request(request):
    
    if request.method =="POST":
        form = AuthenticationForm(request,data=request.POST)
        
        if form.is_valid():
            
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username,password=password)
            
            if user is not None:
                login(request,user)
                return redirect("Home")
            else:
                return redirect('Login')
        else:
            return redirect('Login')
    
    form = AuthenticationForm()
        
        
    return render(request,'tradingbookapp/login.html',{"form":form})


def Logout_request(request):
    logout(request)
    return redirect("Home")


def Register_request(request):
    
    if request.method == "POST":
        
        # form = UserCreationForm(request.POST)
        form = UserRegisterform(request.POST)
        
        if form.is_valid():
            username=form.cleaned_data.get('username')
            password=form.cleaned_data.get('password1') # es la primer contrasena no la confirmacion 
            
            form.save() #registramos el usuario
            #inicamos sesion 
            user = authenticate(username=username,password=password)
            
            if user is not None:
                login(request,user)
                return redirect("Home")
            else:
                return redirect('Login')
            
        
        return render(request,'tradingbookapp/register.html',{"form":form})
        
    # form = UserCreationForm()
    form = UserRegisterform()
    
    return render(request,'tradingbookapp/register.html',{"form":form})


def Markets(request):
    markets = Market.objects.all()
    ctx = {'markets':markets}
    return render(request,'tradingbookapp/markets.html',ctx)


def Notes(request):
    notes = Note.objects.all()
    ctx = {'notes':notes}
    return  render (request,'tradingbookapp/notes.html',ctx)


@login_required
def Profile(request):
    
    return render(request,'tradingbookapp/profile.html')



@login_required
def Trades(request):
    if request.method=="POST":
        search = request.POST["search"] # este search viene del nombre del cuadro de busqueda de la vista
        if search !="":
            trades = Trade.objects.filter(Q(simbolo__icontains=search)|Q(simbolo__icontains=search)).values()
            return render(request,'tradingbookapp/trades.html',{"trades":trades,"search":True,"busqueda":search})
    
    #read
    trades = Trade.objects.all()
    ctx = {'trades':trades}
    return render(request,'tradingbookapp/trades.html',ctx)


class TradesList(LoginRequiredMixin,ListView):#lista todos los estudiantes (read)
    model = Trade 

tradingbookapp/templates/tradingbookapp/Trade_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Eliminar estudiantes</title>
    
</head>
<body>
    <form action="" method="POST">
        {% csrf_token %}
        Estas seguro que deseas eliminar el trade {{object.simbolo}}?
        <input type ="submit" value="Si, Eliminar.">
    <form>

</body>
</html>

tradingbookapp/templates/tradingbookapp/dashboard.html
{% extends "tradingbookapp/base.html" %}
{%load static %}

{% block titulopagina%}
The Good Trader - Dashboard
{%endblock%}

{%block contenidopagina%}



<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>The Good Trader - Dashboard </title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}"   />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}"  rel="stylesheet" />
    </head>
    <body>

    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>The Good Trader - Dashboard</title>
        <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
        <link href="{% static 'dashboard/css/styles.css' %}" rel="stylesheet" />
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    </head>


            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid px-4">
                        <h1 class="mt-4">Dashboard</h1>
                        <ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item active">Dashboard</li>
                        </ol>
                        <div class="row">
                            <div class="col-xl-3 col-md-6">
                                <div class="card bg-primary text-white mb-4">
                                    <div class="card-body">Primary Card</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        <a class="small text-white stretched-link" href="#">View Details</a>
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-3 col-md-6">
                                <div class="card bg-warning text-white mb-4">
                                    <div class="card-body">Warning Card</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        <a class="small text-white stretched-link" href="#">View Details</a>
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-3 col-md-6">
                                <div class="card bg-success text-white mb-4">
                                    <div class="card-body">Success Card</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        <a class="small text-white stretched-link" href="#">View Details</a>
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-3 col-md-6">
                                <div class="card bg-danger text-white mb-4">
                                    <div class="card-body">Danger Card</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        <a class="small text-white stretched-link" href="#">View Details</a>
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xl-6">
                                <div class="card mb-4">
                                    <div class="card-header">
                                        <i class="fas fa-chart-area me-1"></i>
                                        Trading Summary
                                    </div>
                                    <div class="card-body"><canvas id="myAreaChart" width="100%" height="40"></canvas></div>
                                </div>
                            </div>
                            <div class="col-xl-6">
                                <div class="card mb-4">
                                    <div class="card-header">
                                        <i class="fas fa-chart-bar me-1"></i>
                                        Monthly Performance
                                    </div>
                                    <div class="card-body"><canvas id="myBarChart" width="100%" height="40"></canvas></div>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="d-grid gap-3 d-sm-flex justify-content-sm-center">
                            <a class="btn btn-danger btn-lg px-4 me-sm-3" href="{%url 'Markets' %}">Watchlist</a>
                        </div>
                        <br>
                        <div class="card mb-4">
                            <div class="card-header">
                                <i class="fas fa-table me-1"></i>
                                Trade Execution
                            </div>
                            <div class="card-body">
                                <h3>Los Trades Realizados son:</h3>
                                <table class="table">

                                    <thead>
                                        <th scope="col">Fecha</th>
                                        <th scope="col">Simbolo</th>
                                        <th scope="col">Posicion</th>
                                        <th scope="col">Entrada</th>
                                        <th scope="col">Target</th>
                                        <th scope="col">Stop</th>
                                    </thead>
                                    </ul>
                                </table>
                                <table id="datatablesSimple">
                                    <thead>
                                        <tr>

                                            <th scope="col">Fecha</th>
                                            <th scope="col">Simbolo</th>
                                            <th scope="col">Posicion</th>
                                            <th scope="col">Entrada</th>
                                            <th scope="col">Target</th>
                                            <th scope="col">Stop</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>Fecha</th>
                                            <th>Simbolo</th>
                                            <th>Posicion</th>
                                            <th>Entrada</th>
                                            <th>Target</th>
                                            <th>Stop</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        <ul class= "list-group list-group-numbered">
                                            {% for trade in trades  %}
                                            <tr>
                                                <td>{{trade.fecha}}</td>
                                                <td>{{trade.simbolo}}</td>
                                                {% if trade.get_posicion_display == "Long"%}
                                                    <td><span class= "badge bg-primary rounded-pill>">{{trade.get_posicion_display}}</span></td>
                                                {%else%}
                                                    <td><span class= "badge bg-danger rounded-pill>">{{trade.get_posicion_display}}</span></td>
                                                {%endif%}
                                                <td>{{trade.entrada}}</td>
                                                <td>{{trade.target}}</td>
                                                <td>{{trade.stop}}</td>
                                                
                                            </tr>
                                            {% endfor %}
                                        </ul>
                                        
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2022</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'dashboard/js/scripts.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="{% static "dashboard/assets/demo/chart-area-demo.js" %}"></script>
        <script src="{% static "dashboard/assets/demo/chart-bar-demo.js" %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
        <script src="{% static "dashboard/js/datatables-simple-demo.js" %}"></script>
    </body>
</html>
{% endblock %}

tradingbookapp/templates/tradingbookapp/trade_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalles de Trades</title>
    
</head>
<body>
    <h2>Detalle Trade:</h2>
    <p> Fecha: {{trade.fecha}} </p>
    <p> Simbolo: {{trade.simbolo}} </p>
    <p> Posicion: {{trade.get_posicion_display}} </p>
    <p> Entrada: {{trade.entrada}} </p>
    <p> Target: {{trade.target}} </p>
    <p> Stop: {{trade.Stop}} </p>
    <a href= "{% url 'Trades_list' %}">Regresar a lista trades </a>

</body>
</html>

tradingbookapp/templates/tradingbookapp/trade_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulario Trades</title>
    
</head>
<body>
    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit"  value="Guardar Trade"
    <form>
</body>
</html>

tradingbookapp/templates/tradingbookapp/ver_trade.html
{% extends "tradingbookapp/base.html" %}

{% block titulopagina%}
The Good Trader - Trade Analysis
{%endblock%}
{%block contenidopagina%}

<section class="bg-light py-5 border-bottom">
    <div class="container px-5">
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-6">

                <h3>Trade Analysis  | {{trade.simbolo}}</h3> 
                <table class="table">

                    <thead>
                        <th scope="col">Fecha</th>
                        <th scope="col">Simbolo</th>
                        <th scope="col">Posicion</th>
                        <th scope="col">Entrada</th>
                        <th scope="col">Target</th>
                        <th scope="col">Stop</th>
                    </thead>
                    <ul class= "list-group list-group-numbered">
                        <tr>
                            
                            <td>{{trade.fecha}}</td>
                            <td>{{trade.simbolo}}</td>
                            {% if trade.get_posicion_display == "Long"%}
                                <td><span class= "badge bg-primary rounded-pill>">{{trade.get_posicion_display}}</span></td>
                            {%else%}
                                <td><span class= "badge bg-danger rounded-pill>">{{trade.get_posicion_display}}</span></td>
                            {%endif%}
                            <td>{{trade.entrada}}</td>
                            <td>{{trade.target}}</td>
                            <td>{{trade.stop}}</td>
                            
                            
                            
                        </tr>
                        
                    </ul>
                </table>
                <div>
                    {{trade.tradeimagen}}
                </div>
                
            </div>
        </div>
    </div>
    



</section>

{%endblock%}